[project]
name = "cry0404-blog-updater"
version = "0.1.0"
description = "Script to update README with latest blog posts"
requires-python = ">=3.11"
dependencies = [
    "feedparser>=6.0.10",
    "requests>=2.31.0",
]
